name: Tag
run-name: Create tag on ${{ github.sha }}

on:
  workflow_dispatch:
  # schedule:
  #   # 08:00 UTC / 00:00 PST / 01:00 PDT
  #   - cron: '0 8 * * *'
  # TODO remove
  push:
    branches:
      - main

jobs:
  set-tag:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        # tell the action to fetch tags
        fetch-depth: 0

    - id: determine_tag
      name: Determine Tag
      run: bash scripts/release/tetrahub-tag.sh ${{ github.sha }}

    - name: Create Tag
      if: ${{ steps.determine_tag.outputs.tag_name != '' }}
      uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ steps.determine_tag.outputs.tag_name }}
        commit_sha: ${{ github.sha }}

    - name: Trigger deployment
      if: ${{ steps.determine_tag.outputs.tag_name != '' }}
      run: |
        gh workflow run deploy-server.yml --ref ${{ steps.determine_tag.outputs.tag_name }}
