name: Deploy the server
run-name: Deploy tag ${{ github.ref }}

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: B&T
    uses: ./.github/workflows/build-and-test.yml
    with:
      # always run a full build and test on scheduled deployments;
      # release branch deployments are fast-tracked with a minimal build.
      do_all: ${{ github.event_name == 'schedule' }}
      do_apple_ios: true
      do_android: true
      do_client: true
      do_www_docker: true
    secrets: inherit

  deploy-dev:
    name: Deploy to dev
    needs: [build-and-test]
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      gh_env: dev
      aws_env: dev
    concurrency:
      group: deploy-dev
      cancel-in-progress: true

  test-dev:
    name: Test nightly
    needs: [deploy-dev]
    secrets: inherit
    uses: ./.github/workflows/post-deploy-tests.yml
    with:
      environment_name: dev
      tetrahub_url: "https://TODO-replace-me"
      run_e2e: 'nightly'

  deploy-staging:
    name: Deploy to staging
    needs: [test-dev]
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      gh_env: staging
      aws_env: staging
    concurrency:
      group: deploy-staging
      cancel-in-progress: true

  test-staging:
    name: Test staging
    needs: [deploy-staging]
    secrets: inherit
    uses: ./.github/workflows/post-deploy-tests.yml
    with:
      environment_name: staging
      tetrahub_url: "https://TODO-replace-me"
      run_e2e: 'long'

  deploy-prod:
    name: Deploy to prod
    needs: [test-staging]
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      gh_env: prod
      aws_env: prod
    concurrency:
      group: deploy-prod
      cancel-in-progress: true

  test-prod:
    name: Test prod
    needs: [deploy-prod]
    secrets: inherit
    uses: ./.github/workflows/post-deploy-tests.yml
    with:
      environment_name: prod
      tetrahub_url: "https://TODO-replace-me"
      run_e2e: 'none'
