##
## This is the generic deployment workflow. It is intended to be called as a re-usable
## workflow where the environment is specified. Do not add other workflow triggers to this.
##

name: Deploy

on:
  # Allows this workflow to be callable
  workflow_call:
    inputs:
      # the environment name, according to cdk and aws deployment scripts.
      aws_env:
        required: true
        type: string
      # the environment name, according to github deployments.
      gh_env:
        required: true
        type: string
      bespoke:
        required: false
        type: string
      deployment_id:
        required: false
        type: string
      is_hotfix:
        required: false
        type: boolean
        default: false
      create_issue_on_failure:
        required: false
        type: boolean
        default: false

env:
   PYTHON_VERSION: 3.8
   NODE_VERSION: 16

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
    - name: Dump Inputs
      if: ${{ !inputs.is_hotfix || !inputs.gh_env == 'dev'  }}
      shell: bash
      run: |
        echo "Github: ${{ toJson(inputs) }}"

    - name: Deploy things
      if: ${{ !inputs.is_hotfix || !inputs.gh_env == 'dev'  }}
      run: |
        echo "Deploying things."

    - name: Temporary failure
      run: exit 1

  # create_issue_for_failure:
  #   if: ${{ failure() && inputs.create_issue_on_failure }}
  #   name: Create Issue for Failure
  #   needs: [deploy]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     issues: write

  #   steps:
  #   - uses: actions/checkout@v3.1.0
  #   - uses: JasonEtco/create-an-issue@v2
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       RUN_ID: ${{ github.run_id }}
  #     with:
  #       filename: .github/templates/deployment-issue.md

