name: Deploy the server
run-name: Deploy ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: B&T
    uses: ./.github/workflows/build-and-test.yml
    with:
      # always run a full build and test on scheduled deployments;
      # release branch deployments are fast-tracked with a minimal build.
      do_all: ${{ github.event_name == 'schedule' }}
      do_apple_ios: true
      do_android: true
      do_client: true
      do_www_docker: true
    secrets: inherit

  determine-hotfix:
    name: Determine whether the commit is a hotfix
    runs-on: ubuntu-latest
    outputs:
      is_hotfix: ${{ steps.check-commit.outputs.is_hotfix }}
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        # Fetch history for all branches and tags
        fetch-depth: 0

    - name: Check if commit is a hotfix
      id: check-commit
      shell: bash
      run: |
        REPO_ROOT=$(git rev-parse --show-toplevel)
        echo $REPO_ROOT
        echo $GITHUB_SHA
        echo "is_hotfix=$($REPO_ROOT/scripts/release/is-hotfix.sh ${GITHUB_SHA})" >> $GITHUB_OUTPUT


  deploy-dev:
    name: Deploy to dev
    needs: [build-and-test, determine-hotfix]
    if: needs.determine-hotfix.is_hotfix != '1'
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      gh_env: dev
      aws_env: dev
    concurrency:
      group: deploy-dev
      cancel-in-progress: true

  test-dev:
    name: Test nightly
    needs: [deploy-dev]
    if: needs.determine-hotfix.is_hotfix != '1'
    secrets: inherit
    uses: ./.github/workflows/post-deploy-tests.yml
    with:
      environment_name: dev
      tetrahub_url: "https://TODO-replace-me"
      run_e2e: 'nightly'

  deploy-staging:
    name: Deploy to staging
    needs: [deploy-dev]
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      gh_env: staging
      aws_env: staging
    concurrency:
      group: deploy-staging
      cancel-in-progress: true

  test-staging:
    name: Test staging
    needs: [deploy-staging]
    secrets: inherit
    uses: ./.github/workflows/post-deploy-tests.yml
    with:
      environment_name: staging
      tetrahub_url: "https://TODO-replace-me"
      run_e2e: 'long'

  deploy-prod:
    name: Deploy to prod
    needs: [deploy-staging]
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      gh_env: prod
      aws_env: prod
    concurrency:
      group: deploy-prod
      cancel-in-progress: true

  test-prod:
    name: Test prod
    needs: [deploy-prod]
    secrets: inherit
    uses: ./.github/workflows/post-deploy-tests.yml
    with:
      environment_name: prod
      tetrahub_url: "https://TODO-replace-me"
      run_e2e: 'none'
